version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: frontend