version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:5000
    container_name: backend
